//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodRecipes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FoodRecipeEntities1 : DbContext
    {
        public FoodRecipeEntities1()
            : base("name=FoodRecipeEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Igredient> Igredients { get; set; }
        public virtual DbSet<Recipe> Recipes { get; set; }
        public virtual DbSet<Step> Steps { get; set; }
        public virtual DbSet<StepImage> StepImages { get; set; }
    
        [DbFunction("FoodRecipeEntities1", "GetAllFromRecipe")]
        public virtual IQueryable<GetAllFromRecipe_Result> GetAllFromRecipe()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetAllFromRecipe_Result>("[FoodRecipeEntities1].[GetAllFromRecipe]()");
        }
    
        [DbFunction("FoodRecipeEntities1", "GetIgredientByIDRecipe")]
        public virtual IQueryable<GetIgredientByIDRecipe_Result> GetIgredientByIDRecipe(Nullable<int> id_recipe)
        {
            var id_recipeParameter = id_recipe.HasValue ?
                new ObjectParameter("id_recipe", id_recipe) :
                new ObjectParameter("id_recipe", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetIgredientByIDRecipe_Result>("[FoodRecipeEntities1].[GetIgredientByIDRecipe](@id_recipe)", id_recipeParameter);
        }
    
        [DbFunction("FoodRecipeEntities1", "GetLinkImageSByIDRecipeAndNOStep")]
        public virtual IQueryable<GetLinkImageSByIDRecipeAndNOStep_Result> GetLinkImageSByIDRecipeAndNOStep(Nullable<int> id_recipe, Nullable<int> nO_step)
        {
            var id_recipeParameter = id_recipe.HasValue ?
                new ObjectParameter("id_recipe", id_recipe) :
                new ObjectParameter("id_recipe", typeof(int));
    
            var nO_stepParameter = nO_step.HasValue ?
                new ObjectParameter("NO_step", nO_step) :
                new ObjectParameter("NO_step", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetLinkImageSByIDRecipeAndNOStep_Result>("[FoodRecipeEntities1].[GetLinkImageSByIDRecipeAndNOStep](@id_recipe, @NO_step)", id_recipeParameter, nO_stepParameter);
        }
    
        [DbFunction("FoodRecipeEntities1", "GetNumericalOrderAndDetailOfStepByIDRecipe")]
        public virtual IQueryable<GetNumericalOrderAndDetailOfStepByIDRecipe_Result> GetNumericalOrderAndDetailOfStepByIDRecipe(Nullable<int> id_recipe)
        {
            var id_recipeParameter = id_recipe.HasValue ?
                new ObjectParameter("id_recipe", id_recipe) :
                new ObjectParameter("id_recipe", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetNumericalOrderAndDetailOfStepByIDRecipe_Result>("[FoodRecipeEntities1].[GetNumericalOrderAndDetailOfStepByIDRecipe](@id_recipe)", id_recipeParameter);
        }
    
        [DbFunction("FoodRecipeEntities1", "GetRecipeById")]
        public virtual IQueryable<GetRecipeById_Result> GetRecipeById(Nullable<int> id_recipe)
        {
            var id_recipeParameter = id_recipe.HasValue ?
                new ObjectParameter("id_recipe", id_recipe) :
                new ObjectParameter("id_recipe", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetRecipeById_Result>("[FoodRecipeEntities1].[GetRecipeById](@id_recipe)", id_recipeParameter);
        }
    
        [DbFunction("FoodRecipeEntities1", "SearchByName")]
        public virtual IQueryable<SearchByName_Result> SearchByName(string search_text)
        {
            var search_textParameter = search_text != null ?
                new ObjectParameter("search_text", search_text) :
                new ObjectParameter("search_text", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<SearchByName_Result>("[FoodRecipeEntities1].[SearchByName](@search_text)", search_textParameter);
        }
    
        public virtual int InsertIgredient(Nullable<int> id_recipe, string name, string quantity)
        {
            var id_recipeParameter = id_recipe.HasValue ?
                new ObjectParameter("id_recipe", id_recipe) :
                new ObjectParameter("id_recipe", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var quantityParameter = quantity != null ?
                new ObjectParameter("quantity", quantity) :
                new ObjectParameter("quantity", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertIgredient", id_recipeParameter, nameParameter, quantityParameter);
        }
    
        public virtual int InsertRecipe(Nullable<int> id_recipe, string name, string description, string link_video, string link_avatar, Nullable<int> time, string food_group, Nullable<int> food_level, Nullable<bool> shopping_flag, Nullable<bool> favorite_flag, Nullable<System.DateTime> add_date)
        {
            var id_recipeParameter = id_recipe.HasValue ?
                new ObjectParameter("id_recipe", id_recipe) :
                new ObjectParameter("id_recipe", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var link_videoParameter = link_video != null ?
                new ObjectParameter("link_video", link_video) :
                new ObjectParameter("link_video", typeof(string));
    
            var link_avatarParameter = link_avatar != null ?
                new ObjectParameter("link_avatar", link_avatar) :
                new ObjectParameter("link_avatar", typeof(string));
    
            var timeParameter = time.HasValue ?
                new ObjectParameter("time", time) :
                new ObjectParameter("time", typeof(int));
    
            var food_groupParameter = food_group != null ?
                new ObjectParameter("food_group", food_group) :
                new ObjectParameter("food_group", typeof(string));
    
            var food_levelParameter = food_level.HasValue ?
                new ObjectParameter("food_level", food_level) :
                new ObjectParameter("food_level", typeof(int));
    
            var shopping_flagParameter = shopping_flag.HasValue ?
                new ObjectParameter("shopping_flag", shopping_flag) :
                new ObjectParameter("shopping_flag", typeof(bool));
    
            var favorite_flagParameter = favorite_flag.HasValue ?
                new ObjectParameter("favorite_flag", favorite_flag) :
                new ObjectParameter("favorite_flag", typeof(bool));
    
            var add_dateParameter = add_date.HasValue ?
                new ObjectParameter("add_date", add_date) :
                new ObjectParameter("add_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertRecipe", id_recipeParameter, nameParameter, descriptionParameter, link_videoParameter, link_avatarParameter, timeParameter, food_groupParameter, food_levelParameter, shopping_flagParameter, favorite_flagParameter, add_dateParameter);
        }
    
        public virtual int InsertStep(Nullable<int> id_recipe, Nullable<int> no_step, string detail)
        {
            var id_recipeParameter = id_recipe.HasValue ?
                new ObjectParameter("id_recipe", id_recipe) :
                new ObjectParameter("id_recipe", typeof(int));
    
            var no_stepParameter = no_step.HasValue ?
                new ObjectParameter("no_step", no_step) :
                new ObjectParameter("no_step", typeof(int));
    
            var detailParameter = detail != null ?
                new ObjectParameter("detail", detail) :
                new ObjectParameter("detail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertStep", id_recipeParameter, no_stepParameter, detailParameter);
        }
    
        public virtual int InsertStepImages(Nullable<int> id_recipe, Nullable<int> no_step, string link_images)
        {
            var id_recipeParameter = id_recipe.HasValue ?
                new ObjectParameter("id_recipe", id_recipe) :
                new ObjectParameter("id_recipe", typeof(int));
    
            var no_stepParameter = no_step.HasValue ?
                new ObjectParameter("no_step", no_step) :
                new ObjectParameter("no_step", typeof(int));
    
            var link_imagesParameter = link_images != null ?
                new ObjectParameter("link_images", link_images) :
                new ObjectParameter("link_images", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertStepImages", id_recipeParameter, no_stepParameter, link_imagesParameter);
        }
    
        public virtual int TurnFavoriteFlagOff(Nullable<int> id_recipe)
        {
            var id_recipeParameter = id_recipe.HasValue ?
                new ObjectParameter("id_recipe", id_recipe) :
                new ObjectParameter("id_recipe", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TurnFavoriteFlagOff", id_recipeParameter);
        }
    
        public virtual int TurnFavoriteFlagOn(Nullable<int> id_recipe)
        {
            var id_recipeParameter = id_recipe.HasValue ?
                new ObjectParameter("id_recipe", id_recipe) :
                new ObjectParameter("id_recipe", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TurnFavoriteFlagOn", id_recipeParameter);
        }
    
        public virtual int TurnShoppingFlagOff(Nullable<int> id_recipe)
        {
            var id_recipeParameter = id_recipe.HasValue ?
                new ObjectParameter("id_recipe", id_recipe) :
                new ObjectParameter("id_recipe", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TurnShoppingFlagOff", id_recipeParameter);
        }
    
        public virtual int TurnShoppingFlagOn(Nullable<int> id_recipe)
        {
            var id_recipeParameter = id_recipe.HasValue ?
                new ObjectParameter("id_recipe", id_recipe) :
                new ObjectParameter("id_recipe", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TurnShoppingFlagOn", id_recipeParameter);
        }
    }
}
