//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodRecipes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FoodRecipeEntities : DbContext
    {
        public FoodRecipeEntities()
            : base("name=FoodRecipeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Igredient> Igredients { get; set; }
        public virtual DbSet<Recipe> Recipes { get; set; }
        public virtual DbSet<Step> Steps { get; set; }
        public virtual DbSet<StepImage> StepImages { get; set; }
    
        [DbFunction("FoodRecipeEntities", "GetAllFromRecipe")]
        public virtual IQueryable<GetAllFromRecipe_Result> GetAllFromRecipe()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetAllFromRecipe_Result>("[FoodRecipeEntities].[GetAllFromRecipe]()");
        }
    
        [DbFunction("FoodRecipeEntities", "GetIDRecipeByFavoriteFlag")]
        public virtual IQueryable<GetIDRecipeByFavoriteFlag_Result> GetIDRecipeByFavoriteFlag(Nullable<bool> favorite_flag)
        {
            var favorite_flagParameter = favorite_flag.HasValue ?
                new ObjectParameter("favorite_flag", favorite_flag) :
                new ObjectParameter("favorite_flag", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetIDRecipeByFavoriteFlag_Result>("[FoodRecipeEntities].[GetIDRecipeByFavoriteFlag](@favorite_flag)", favorite_flagParameter);
        }
    
        [DbFunction("FoodRecipeEntities", "GetIDRecipeByFoodGroup")]
        public virtual IQueryable<GetIDRecipeByFoodGroup_Result> GetIDRecipeByFoodGroup(string food_group)
        {
            var food_groupParameter = food_group != null ?
                new ObjectParameter("food_group", food_group) :
                new ObjectParameter("food_group", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetIDRecipeByFoodGroup_Result>("[FoodRecipeEntities].[GetIDRecipeByFoodGroup](@food_group)", food_groupParameter);
        }
    
        [DbFunction("FoodRecipeEntities", "GetIDRecipeByFoodLevel")]
        public virtual IQueryable<GetIDRecipeByFoodLevel_Result> GetIDRecipeByFoodLevel(string food_level)
        {
            var food_levelParameter = food_level != null ?
                new ObjectParameter("food_level", food_level) :
                new ObjectParameter("food_level", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetIDRecipeByFoodLevel_Result>("[FoodRecipeEntities].[GetIDRecipeByFoodLevel](@food_level)", food_levelParameter);
        }
    
        [DbFunction("FoodRecipeEntities", "GetIDRecipeByShoppingFlag")]
        public virtual IQueryable<GetIDRecipeByShoppingFlag_Result> GetIDRecipeByShoppingFlag(Nullable<bool> shopping_flag)
        {
            var shopping_flagParameter = shopping_flag.HasValue ?
                new ObjectParameter("shopping_flag", shopping_flag) :
                new ObjectParameter("shopping_flag", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetIDRecipeByShoppingFlag_Result>("[FoodRecipeEntities].[GetIDRecipeByShoppingFlag](@shopping_flag)", shopping_flagParameter);
        }
    
        [DbFunction("FoodRecipeEntities", "GetIDRecipeByTime")]
        public virtual IQueryable<GetIDRecipeByTime_Result> GetIDRecipeByTime(string time)
        {
            var timeParameter = time != null ?
                new ObjectParameter("time", time) :
                new ObjectParameter("time", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetIDRecipeByTime_Result>("[FoodRecipeEntities].[GetIDRecipeByTime](@time)", timeParameter);
        }
    
        [DbFunction("FoodRecipeEntities", "GetIgredientByIDRecipe")]
        public virtual IQueryable<GetIgredientByIDRecipe_Result> GetIgredientByIDRecipe(Nullable<int> id_recipe)
        {
            var id_recipeParameter = id_recipe.HasValue ?
                new ObjectParameter("id_recipe", id_recipe) :
                new ObjectParameter("id_recipe", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetIgredientByIDRecipe_Result>("[FoodRecipeEntities].[GetIgredientByIDRecipe](@id_recipe)", id_recipeParameter);
        }
    
        [DbFunction("FoodRecipeEntities", "GetLinkImageSByIDRecipeAndNOStep")]
        public virtual IQueryable<GetLinkImageSByIDRecipeAndNOStep_Result> GetLinkImageSByIDRecipeAndNOStep(Nullable<int> id_recipe, Nullable<int> nO_step)
        {
            var id_recipeParameter = id_recipe.HasValue ?
                new ObjectParameter("id_recipe", id_recipe) :
                new ObjectParameter("id_recipe", typeof(int));
    
            var nO_stepParameter = nO_step.HasValue ?
                new ObjectParameter("NO_step", nO_step) :
                new ObjectParameter("NO_step", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetLinkImageSByIDRecipeAndNOStep_Result>("[FoodRecipeEntities].[GetLinkImageSByIDRecipeAndNOStep](@id_recipe, @NO_step)", id_recipeParameter, nO_stepParameter);
        }
    
        [DbFunction("FoodRecipeEntities", "GetNumericalOrderAndDetailOfStepByIDRecipe")]
        public virtual IQueryable<GetNumericalOrderAndDetailOfStepByIDRecipe_Result> GetNumericalOrderAndDetailOfStepByIDRecipe(Nullable<int> id_recipe)
        {
            var id_recipeParameter = id_recipe.HasValue ?
                new ObjectParameter("id_recipe", id_recipe) :
                new ObjectParameter("id_recipe", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetNumericalOrderAndDetailOfStepByIDRecipe_Result>("[FoodRecipeEntities].[GetNumericalOrderAndDetailOfStepByIDRecipe](@id_recipe)", id_recipeParameter);
        }
    
        [DbFunction("FoodRecipeEntities", "SearchByName")]
        public virtual IQueryable<SearchByName_Result> SearchByName(string search_text)
        {
            var search_textParameter = search_text != null ?
                new ObjectParameter("search_text", search_text) :
                new ObjectParameter("search_text", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<SearchByName_Result>("[FoodRecipeEntities].[SearchByName](@search_text)", search_textParameter);
        }
    
        public virtual int InsertIgredient(Nullable<int> id_recipe, string name, string quantity)
        {
            var id_recipeParameter = id_recipe.HasValue ?
                new ObjectParameter("id_recipe", id_recipe) :
                new ObjectParameter("id_recipe", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var quantityParameter = quantity != null ?
                new ObjectParameter("quantity", quantity) :
                new ObjectParameter("quantity", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertIgredient", id_recipeParameter, nameParameter, quantityParameter);
        }
    
        public virtual int InsertRecipe(Nullable<int> id_recipe, string name, string description, string link_video, string link_avatar, string time, string food_group, string food_level, Nullable<bool> shopping_flag, Nullable<bool> favorite_flag)
        {
            var id_recipeParameter = id_recipe.HasValue ?
                new ObjectParameter("id_recipe", id_recipe) :
                new ObjectParameter("id_recipe", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var link_videoParameter = link_video != null ?
                new ObjectParameter("link_video", link_video) :
                new ObjectParameter("link_video", typeof(string));
    
            var link_avatarParameter = link_avatar != null ?
                new ObjectParameter("link_avatar", link_avatar) :
                new ObjectParameter("link_avatar", typeof(string));
    
            var timeParameter = time != null ?
                new ObjectParameter("time", time) :
                new ObjectParameter("time", typeof(string));
    
            var food_groupParameter = food_group != null ?
                new ObjectParameter("food_group", food_group) :
                new ObjectParameter("food_group", typeof(string));
    
            var food_levelParameter = food_level != null ?
                new ObjectParameter("food_level", food_level) :
                new ObjectParameter("food_level", typeof(string));
    
            var shopping_flagParameter = shopping_flag.HasValue ?
                new ObjectParameter("shopping_flag", shopping_flag) :
                new ObjectParameter("shopping_flag", typeof(bool));
    
            var favorite_flagParameter = favorite_flag.HasValue ?
                new ObjectParameter("favorite_flag", favorite_flag) :
                new ObjectParameter("favorite_flag", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertRecipe", id_recipeParameter, nameParameter, descriptionParameter, link_videoParameter, link_avatarParameter, timeParameter, food_groupParameter, food_levelParameter, shopping_flagParameter, favorite_flagParameter);
        }
    
        public virtual int InsertStep(Nullable<int> id_recipe, Nullable<int> no_step, string detail)
        {
            var id_recipeParameter = id_recipe.HasValue ?
                new ObjectParameter("id_recipe", id_recipe) :
                new ObjectParameter("id_recipe", typeof(int));
    
            var no_stepParameter = no_step.HasValue ?
                new ObjectParameter("no_step", no_step) :
                new ObjectParameter("no_step", typeof(int));
    
            var detailParameter = detail != null ?
                new ObjectParameter("detail", detail) :
                new ObjectParameter("detail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertStep", id_recipeParameter, no_stepParameter, detailParameter);
        }
    
        public virtual int InsertStepImages(Nullable<int> id_recipe, Nullable<int> no_step, string link_images)
        {
            var id_recipeParameter = id_recipe.HasValue ?
                new ObjectParameter("id_recipe", id_recipe) :
                new ObjectParameter("id_recipe", typeof(int));
    
            var no_stepParameter = no_step.HasValue ?
                new ObjectParameter("no_step", no_step) :
                new ObjectParameter("no_step", typeof(int));
    
            var link_imagesParameter = link_images != null ?
                new ObjectParameter("link_images", link_images) :
                new ObjectParameter("link_images", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertStepImages", id_recipeParameter, no_stepParameter, link_imagesParameter);
        }
    
        public virtual int TurnFavoriteFlagOff(Nullable<int> id_recipe)
        {
            var id_recipeParameter = id_recipe.HasValue ?
                new ObjectParameter("id_recipe", id_recipe) :
                new ObjectParameter("id_recipe", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TurnFavoriteFlagOff", id_recipeParameter);
        }
    
        public virtual int TurnFavoriteFlagOn(Nullable<int> id_recipe)
        {
            var id_recipeParameter = id_recipe.HasValue ?
                new ObjectParameter("id_recipe", id_recipe) :
                new ObjectParameter("id_recipe", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TurnFavoriteFlagOn", id_recipeParameter);
        }
    
        public virtual int TurnShoppingFlagOff(Nullable<int> id_recipe)
        {
            var id_recipeParameter = id_recipe.HasValue ?
                new ObjectParameter("id_recipe", id_recipe) :
                new ObjectParameter("id_recipe", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TurnShoppingFlagOff", id_recipeParameter);
        }
    
        public virtual int TurnShoppingFlagOn(Nullable<int> id_recipe)
        {
            var id_recipeParameter = id_recipe.HasValue ?
                new ObjectParameter("id_recipe", id_recipe) :
                new ObjectParameter("id_recipe", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TurnShoppingFlagOn", id_recipeParameter);
        }
    
        [DbFunction("FoodRecipeEntities", "GetRecipeById")]
        public virtual IQueryable<GetRecipeById_Result> GetRecipeById(Nullable<int> id_recipe)
        {
            var id_recipeParameter = id_recipe.HasValue ?
                new ObjectParameter("id_recipe", id_recipe) :
                new ObjectParameter("id_recipe", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetRecipeById_Result>("[FoodRecipeEntities].[GetRecipeById](@id_recipe)", id_recipeParameter);
        }
    }
}
