//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodRecipes
{
    using System;
    using System.Collections.Generic;
    
    public partial class StepImage
    {
        public int ID_RECIPE { get; set; }
        public int NO_STEP { get; set; }
        public string LINK_IMAGES { get; set; }
    
        public virtual Step Step { get; set; }
    }
}
