//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodRecipes
{
    using System;
    using System.Collections.Generic;

    public partial class Step
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Step()
        {
            this.StepImages = new HashSet<StepImage>();
        }
        public int ID_RECIPE { get; set; }
        public int NO_STEP { get; set; }
        public string NO_STEP_FOR_BINDING { get; set; }
        public string DETAIL { get; set; }
        public List<StepImage> STEP_IMAGES_LIST_FOR_BINDING { get; set; }

        public virtual Recipe Recipe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StepImage> StepImages { get; set; }
    }
}