//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodRecipes.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoodRecipes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string about_us_page_name {
            get {
                return ResourceManager.GetString("about_us_page_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Recipe.
        /// </summary>
        public static string add_recipe_page_name {
            get {
                return ResourceManager.GetString("add_recipe_page_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOOD RECIPES.
        /// </summary>
        public static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        public static string fav_page_name {
            get {
                return ResourceManager.GetString("fav_page_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string help_page_name {
            get {
                return ResourceManager.GetString("help_page_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search your recipe here...
        /// </summary>
        public static string hint_text_search {
            get {
                return ResourceManager.GetString("hint_text_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string home_page_name {
            get {
                return ResourceManager.GetString("home_page_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string home_text_btn {
            get {
                return ResourceManager.GetString("home_text_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không hiển thị Splash Screen khi khởi chạy ứng dụng vào lần tới..
        /// </summary>
        public static string message_not_show_splash {
            get {
                return ResourceManager.GetString("message_not_show_splash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping.
        /// </summary>
        public static string shopping_page_name {
            get {
                return ResourceManager.GetString("shopping_page_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gà lăn hồ đào mỹ chiên giòn với salad nho khô dưa hấu là món salad vừa thơm ngon lại rất bổ dưỡng. Một món ăn chứa đầy đủ chất dinh dưỡng từ các loại rau xanh, dưa hấu, nho khô, thịt gà ăn kèm cùng với sốt giấm đặc biệt sẽ khiến cho bạn càng ăn càng mê. Bạn hãy lưu lại ngay công thức bên dưới để làm món salad này nhé..
        /// </summary>
        public static string test_description {
            get {
                return ResourceManager.GetString("test_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GÀ LĂN HỒ ĐÀO MỸ CHIÊN GIÒN VỚI SALAD NHO KHÔ DƯA HẤU.
        /// </summary>
        public static string test_name_recipe {
            get {
                return ResourceManager.GetString("test_name_recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ăn sáng.
        /// </summary>
        public static string text_breakfast_group {
            get {
                return ResourceManager.GetString("text_breakfast_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thức uống.
        /// </summary>
        public static string text_drink_group {
            get {
                return ResourceManager.GetString("text_drink_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ăn vặt.
        /// </summary>
        public static string text_fastfood_group {
            get {
                return ResourceManager.GetString("text_fastfood_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healthy.
        /// </summary>
        public static string text_healthy_group {
            get {
                return ResourceManager.GetString("text_healthy_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 x 4.
        /// </summary>
        public static string text_item_grid_34 {
            get {
                return ResourceManager.GetString("text_item_grid_34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 x 4.
        /// </summary>
        public static string text_item_grid_44 {
            get {
                return ResourceManager.GetString("text_item_grid_44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 x 4.
        /// </summary>
        public static string text_item_grid_54 {
            get {
                return ResourceManager.GetString("text_item_grid_54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A-Z.
        /// </summary>
        public static string text_item_sort_az {
            get {
                return ResourceManager.GetString("text_item_sort_az", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string text_item_sort_date {
            get {
                return ResourceManager.GetString("text_item_sort_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string text_item_sort_level {
            get {
                return ResourceManager.GetString("text_item_sort_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string text_item_sort_time {
            get {
                return ResourceManager.GetString("text_item_sort_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z-A.
        /// </summary>
        public static string text_item_sort_za {
            get {
                return ResourceManager.GetString("text_item_sort_za", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Món chính.
        /// </summary>
        public static string text_maindish_group {
            get {
                return ResourceManager.GetString("text_maindish_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Món chay.
        /// </summary>
        public static string text_vegetarian_group {
            get {
                return ResourceManager.GetString("text_vegetarian_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s explore and create your food recipes..
        /// </summary>
        public static string tip_app_logo {
            get {
                return ResourceManager.GetString("tip_app_logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string tip_close_window_button {
            get {
                return ResourceManager.GetString("tip_close_window_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eraser all selected filter.
        /// </summary>
        public static string tip_eraser_all_filter {
            get {
                return ResourceManager.GetString("tip_eraser_all_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        public static string tip_maximize_window_button {
            get {
                return ResourceManager.GetString("tip_maximize_window_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string tip_minimize_window_button {
            get {
                return ResourceManager.GetString("tip_minimize_window_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore down.
        /// </summary>
        public static string tip_restore_window_button {
            get {
                return ResourceManager.GetString("tip_restore_window_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid:.
        /// </summary>
        public static string title_grid_box {
            get {
                return ResourceManager.GetString("title_grid_box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by:.
        /// </summary>
        public static string title_sort_box {
            get {
                return ResourceManager.GetString("title_sort_box", resourceCulture);
            }
        }
    }
}
