//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodRecipes.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoodRecipes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT.
        /// </summary>
        public static string about_page_upper {
            get {
                return ResourceManager.GetString("about_page_upper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string about_us_page_name {
            get {
                return ResourceManager.GetString("about_us_page_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Recipe.
        /// </summary>
        public static string add_recipe_page_name {
            get {
                return ResourceManager.GetString("add_recipe_page_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD RECIPE.
        /// </summary>
        public static string add_recipe_page_upper {
            get {
                return ResourceManager.GetString("add_recipe_page_upper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOOD RECIPES.
        /// </summary>
        public static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 1.0.0.
        /// </summary>
        public static string app_version {
            get {
                return ResourceManager.GetString("app_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite.
        /// </summary>
        public static string fav_page_name {
            get {
                return ResourceManager.GetString("fav_page_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAVORITE.
        /// </summary>
        public static string fav_page_upper {
            get {
                return ResourceManager.GetString("fav_page_upper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string help_page_name {
            get {
                return ResourceManager.GetString("help_page_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HELP.
        /// </summary>
        public static string help_page_upper {
            get {
                return ResourceManager.GetString("help_page_upper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả món ăn của bạn.
        /// </summary>
        public static string hint_description_recipe {
            get {
                return ResourceManager.GetString("hint_description_recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả chi tiết bước thực hiện.
        /// </summary>
        public static string hint_detail_step {
            get {
                return ResourceManager.GetString("hint_detail_step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập tên nguyên liệu.
        /// </summary>
        public static string hint_igredient_name {
            get {
                return ResourceManager.GetString("hint_igredient_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập số lượng.
        /// </summary>
        public static string hint_igredient_quantity {
            get {
                return ResourceManager.GetString("hint_igredient_quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập vào url video món ăn của bạn.
        /// </summary>
        public static string hint_link_video {
            get {
                return ResourceManager.GetString("hint_link_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập tên món ăn của bạn.
        /// </summary>
        public static string hint_recipe_name {
            get {
                return ResourceManager.GetString("hint_recipe_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search your recipe here...
        /// </summary>
        public static string hint_text_search {
            get {
                return ResourceManager.GetString("hint_text_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian làm món ăn.
        /// </summary>
        public static string hint_time {
            get {
                return ResourceManager.GetString("hint_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string home_page_name {
            get {
                return ResourceManager.GetString("home_page_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOME.
        /// </summary>
        public static string home_page_upper {
            get {
                return ResourceManager.GetString("home_page_upper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string home_text_btn {
            get {
                return ResourceManager.GetString("home_text_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không hiển thị Splash Screen khi khởi chạy ứng dụng vào lần tới..
        /// </summary>
        public static string message_not_show_splash {
            get {
                return ResourceManager.GetString("message_not_show_splash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping.
        /// </summary>
        public static string shopping_page_name {
            get {
                return ResourceManager.GetString("shopping_page_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHOPPING.
        /// </summary>
        public static string shopping_page_upper {
            get {
                return ResourceManager.GetString("shopping_page_upper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiện tại chưa có bước nào được thêm vào.
        /// </summary>
        public static string status_add_step_list_empty {
            get {
                return ResourceManager.GetString("status_add_step_list_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rất tiếc không thể load danh sách.
        /// </summary>
        public static string status_list_load_fail {
            get {
                return ResourceManager.GetString("status_list_load_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách hiện tại chưa có món ăn.
        /// </summary>
        public static string status_list_recipe_empty {
            get {
                return ResourceManager.GetString("status_list_recipe_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rất tiếc không thể load video.
        /// </summary>
        public static string status_video_load_fail {
            get {
                return ResourceManager.GetString("status_video_load_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gà lăn hồ đào mỹ chiên giòn với salad nho khô dưa hấu là món salad vừa thơm ngon lại rất bổ dưỡng. Một món ăn chứa đầy đủ chất dinh dưỡng từ các loại rau xanh, dưa hấu, nho khô, thịt gà ăn kèm cùng với sốt giấm đặc biệt sẽ khiến cho bạn càng ăn càng mê. Bạn hãy lưu lại ngay công thức bên dưới để làm món salad này nhé..
        /// </summary>
        public static string test_description {
            get {
                return ResourceManager.GetString("test_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GÀ LĂN HỒ ĐÀO MỸ CHIÊN GIÒN VỚI SALAD NHO KHÔ DƯA HẤU.
        /// </summary>
        public static string test_name_recipe {
            get {
                return ResourceManager.GetString("test_name_recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sốt Giấm: Cho 2 muỗng canh nho khô California đen, 1 quả ớt jalapeno bỏ hạt, 1 muỗng canh mù tạt Dijon, 11/2 muỗng cà phê mù tạt nguyên hạt, 1 muỗng canh mật ong, 1 muỗng canh dấm gạo, 2 muỗng canh dầu ô liu, 1 muỗng canh hẹ tươi đã cắt nhỏ, 1 muỗng cà phê muối và tiêu vào cối xay sinh tốt, xay nhuyễn và giữ lạnh..
        /// </summary>
        public static string test_step {
            get {
                return ResourceManager.GetString("test_step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string text_0 {
            get {
                return ResourceManager.GetString("text_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food Recipes là một ứng dụng được viết bằng công nghệ WPF của Microsoft giúp bạn có thể dễ dàng tìm kiếm và chia sẻ các công thức nấu ăn một cách nhanh chóng và tiện lợi..
        /// </summary>
        public static string text_about_app {
            get {
                return ResourceManager.GetString("text_about_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Danh sách trên được sắp xếp tăng dần theo MSSV..
        /// </summary>
        public static string text_about_sort {
            get {
                return ResourceManager.GetString("text_about_sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinh viên đang học môn Lập trình Windows - Thầy Trần Duy Quang, khoa Công nghệ thông tin, Trường Đại học Khoa học tự nhiên, ĐHQG TP.Hồ Chí Minh..
        /// </summary>
        public static string text_about_us {
            get {
                return ResourceManager.GetString("text_about_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD SHOPPING.
        /// </summary>
        public static string text_add_shopping {
            get {
                return ResourceManager.GetString("text_add_shopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD STEP.
        /// </summary>
        public static string text_add_step {
            get {
                return ResourceManager.GetString("text_add_step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ăn sáng.
        /// </summary>
        public static string text_breakfast_group {
            get {
                return ResourceManager.GetString("text_breakfast_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLEAR SELECTED.
        /// </summary>
        public static string text_clear_select_shopping {
            get {
                return ResourceManager.GetString("text_clear_select_shopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mọi thắc mắc về ứng dụng xin vui lòng liên hệ foodrecipes.hcmus@gmail.com.
        ///The MIT License (MIT).
        ///Copy right © 2020 Quoc Thuan Truong, Le Nhat Tuan, Hoang Thi Thuy Trang..
        /// </summary>
        public static string text_contact {
            get {
                return ResourceManager.GetString("text_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thức uống.
        /// </summary>
        public static string text_drink_group {
            get {
                return ResourceManager.GetString("text_drink_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ăn vặt.
        /// </summary>
        public static string text_fastfood_group {
            get {
                return ResourceManager.GetString("text_fastfood_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/QuocThuanTruong/FoodRecipes.
        /// </summary>
        public static string text_github {
            get {
                return ResourceManager.GetString("text_github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healthy.
        /// </summary>
        public static string text_healthy_group {
            get {
                return ResourceManager.GetString("text_healthy_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chứa thông tin về ứng dụng dụng và các thành viên phát triển..
        /// </summary>
        public static string text_help_about {
            get {
                return ResourceManager.GetString("text_help_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có thẻ thêm món ăn của mình và danh sách bằng cách điền đầy đủ thông tin và hình ảnh vào trang này. Các thông tin đó bao gồm tên món ăn, mô tả, ảnh đại diện, link video của món ăn, thời gian, nhóm của món ăn, mức độ và các bước thực hiện..
        /// </summary>
        public static string text_help_add_recipe {
            get {
                return ResourceManager.GetString("text_help_add_recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nơi chứa những món ăn được bạn yêu thích, bạn có thế tìm kiếm với các chế độ khác nhau như HOME..
        /// </summary>
        public static string text_help_fav {
            get {
                return ResourceManager.GetString("text_help_fav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cung cấp thông tin về các trang và hướng dẫn bạn sử dụng Food Recipes..
        /// </summary>
        public static string text_help_help {
            get {
                return ResourceManager.GetString("text_help_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sử dụng thanh tìm kiếm để tìm món ăn mà bạn muốn, bạn có thể sử dụng các chế độ sắp xếp, chế độ hiển thị của danh sách món ăn và bộ lọc các món ăn theo nhóm để tìm kiếm nhanh hơn.
        ///Mẹo tìm kiếm từ khóa: Bạn có thể sử dụng cú pháp “&lt;key_word_1&gt;” &lt;operator&gt; &lt;”key_word_2&gt;” với &lt;operator&gt; có thể là ‘and’, ‘or’ hoặc ‘and not’ để tìm kiếm.
        ///Sau khi tìm được món ăn bạn có thể click vào để xem chi tiết món ăn đó. Bên trong mỗi món ăn bạn có thể thêm danh sách nguyên liệu vào shopping list bằng cách click vào nút AD [rest of string was truncated]&quot;;.
        /// </summary>
        public static string text_help_home {
            get {
                return ResourceManager.GetString("text_help_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khi bạn thêm nguyên liệu vào shopping list ở trang chi tiết món ăn, danh sách nguyên liệu của bạn sẽ được lưu lại ở trang này và bạn có thể dễ dàng mua sắm với danh sách nguyên liệu cần thiết. Ngoài ra bạn có thể tick vào nút cạnh bên nguyên liệu để đánh dấu rằng bạn đã mua nó..
        /// </summary>
        public static string text_help_shopping {
            get {
                return ResourceManager.GetString("text_help_shopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to giờ.
        /// </summary>
        public static string text_hour {
            get {
                return ResourceManager.GetString("text_hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dễ.
        /// </summary>
        public static string text_item_ez {
            get {
                return ResourceManager.GetString("text_item_ez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 x 4.
        /// </summary>
        public static string text_item_grid_34 {
            get {
                return ResourceManager.GetString("text_item_grid_34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 x 4.
        /// </summary>
        public static string text_item_grid_44 {
            get {
                return ResourceManager.GetString("text_item_grid_44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 x 4.
        /// </summary>
        public static string text_item_grid_54 {
            get {
                return ResourceManager.GetString("text_item_grid_54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khó.
        /// </summary>
        public static string text_item_hard {
            get {
                return ResourceManager.GetString("text_item_hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TB.
        /// </summary>
        public static string text_item_normal {
            get {
                return ResourceManager.GetString("text_item_normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A-Z.
        /// </summary>
        public static string text_item_sort_az {
            get {
                return ResourceManager.GetString("text_item_sort_az", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string text_item_sort_date {
            get {
                return ResourceManager.GetString("text_item_sort_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string text_item_sort_level {
            get {
                return ResourceManager.GetString("text_item_sort_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string text_item_sort_time {
            get {
                return ResourceManager.GetString("text_item_sort_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z-A.
        /// </summary>
        public static string text_item_sort_za {
            get {
                return ResourceManager.GetString("text_item_sort_za", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://youtu.be/Rzg9LGXxTtI.
        /// </summary>
        public static string text_link_video_help {
            get {
                return ResourceManager.GetString("text_link_video_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Món chính.
        /// </summary>
        public static string text_maindish_group {
            get {
                return ResourceManager.GetString("text_maindish_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phút.
        /// </summary>
        public static string text_minute {
            get {
                return ResourceManager.GetString("text_minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18120605.
        /// </summary>
        public static string text_mssv_ht {
            get {
                return ResourceManager.GetString("text_mssv_ht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18120632.
        /// </summary>
        public static string text_mssv_nt {
            get {
                return ResourceManager.GetString("text_mssv_nt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18120583.
        /// </summary>
        public static string text_mssv_qt {
            get {
                return ResourceManager.GetString("text_mssv_qt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàng Thị Thùy Trang.
        /// </summary>
        public static string text_name_ht {
            get {
                return ResourceManager.GetString("text_name_ht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lê Nhật Tuấn.
        /// </summary>
        public static string text_name_nt {
            get {
                return ResourceManager.GetString("text_name_nt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quốc Thuận Trương.
        /// </summary>
        public static string text_name_qt {
            get {
                return ResourceManager.GetString("text_name_qt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE RECIPE.
        /// </summary>
        public static string text_save_recipe {
            get {
                return ResourceManager.GetString("text_save_recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social media.
        /// </summary>
        public static string text_social_media {
            get {
                return ResourceManager.GetString("text_social_media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Món chay.
        /// </summary>
        public static string text_vegetarian_group {
            get {
                return ResourceManager.GetString("text_vegetarian_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to your favorite food recipes.
        /// </summary>
        public static string tip_add_fav {
            get {
                return ResourceManager.GetString("tip_add_fav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add igredients.
        /// </summary>
        public static string tip_add_igredient {
            get {
                return ResourceManager.GetString("tip_add_igredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s explore and create your food recipes..
        /// </summary>
        public static string tip_app_logo {
            get {
                return ResourceManager.GetString("tip_app_logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string tip_cancel {
            get {
                return ResourceManager.GetString("tip_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all filter.
        /// </summary>
        public static string tip_clear_filter {
            get {
                return ResourceManager.GetString("tip_clear_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string tip_close_window_button {
            get {
                return ResourceManager.GetString("tip_close_window_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete your shopping item.
        /// </summary>
        public static string tip_delete_shopping {
            get {
                return ResourceManager.GetString("tip_delete_shopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eraser all selected filter.
        /// </summary>
        public static string tip_eraser_all_filter {
            get {
                return ResourceManager.GetString("tip_eraser_all_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string tip_fb {
            get {
                return ResourceManager.GetString("tip_fb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter food recipes.
        /// </summary>
        public static string tip_filter {
            get {
                return ResourceManager.GetString("tip_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First page.
        /// </summary>
        public static string tip_first_page {
            get {
                return ResourceManager.GetString("tip_first_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food group.
        /// </summary>
        public static string tip_group {
            get {
                return ResourceManager.GetString("tip_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram.
        /// </summary>
        public static string tip_ig {
            get {
                return ResourceManager.GetString("tip_ig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last page.
        /// </summary>
        public static string tip_last_page {
            get {
                return ResourceManager.GetString("tip_last_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string tip_level {
            get {
                return ResourceManager.GetString("tip_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        public static string tip_maximize_window_button {
            get {
                return ResourceManager.GetString("tip_maximize_window_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string tip_minimize_window_button {
            get {
                return ResourceManager.GetString("tip_minimize_window_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next page.
        /// </summary>
        public static string tip_next_page {
            get {
                return ResourceManager.GetString("tip_next_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open your file.
        /// </summary>
        public static string tip_open_file {
            get {
                return ResourceManager.GetString("tip_open_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick up recipe avatar.
        /// </summary>
        public static string tip_pick_avt {
            get {
                return ResourceManager.GetString("tip_pick_avt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick up step images.
        /// </summary>
        public static string tip_pick_image {
            get {
                return ResourceManager.GetString("tip_pick_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous page.
        /// </summary>
        public static string tip_previous_page {
            get {
                return ResourceManager.GetString("tip_previous_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore down.
        /// </summary>
        public static string tip_restore_window_button {
            get {
                return ResourceManager.GetString("tip_restore_window_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Making time.
        /// </summary>
        public static string tip_time {
            get {
                return ResourceManager.GetString("tip_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiktok.
        /// </summary>
        public static string tip_tt {
            get {
                return ResourceManager.GetString("tip_tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube.
        /// </summary>
        public static string tip_yt {
            get {
                return ResourceManager.GetString("tip_yt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VỀ ỨNG DỤNG FOOD RECIPES.
        /// </summary>
        public static string title_about_app {
            get {
                return ResourceManager.GetString("title_about_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VỀ CHÚNG TÔI.
        /// </summary>
        public static string title_about_us {
            get {
                return ResourceManager.GetString("title_about_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HÌNH ĐẠI DIỆN.
        /// </summary>
        public static string title_avt {
            get {
                return ResourceManager.GetString("title_avt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIÊN HỆ.
        /// </summary>
        public static string title_contact {
            get {
                return ResourceManager.GetString("title_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MÔ TẢ.
        /// </summary>
        public static string title_description {
            get {
                return ResourceManager.GetString("title_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHI TIẾT BƯỚC THỰC HIỆN.
        /// </summary>
        public static string title_detail_step {
            get {
                return ResourceManager.GetString("title_detail_step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid:.
        /// </summary>
        public static string title_grid_box {
            get {
                return ResourceManager.GetString("title_grid_box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HƯỚNG DẪN SỬ DỤNG FOOD RECIPES.
        /// </summary>
        public static string title_how_to_use {
            get {
                return ResourceManager.GetString("title_how_to_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGUYÊN LIỆU.
        /// </summary>
        public static string title_igredient {
            get {
                return ResourceManager.GetString("title_igredient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TÊN NGUYÊN LIỆU.
        /// </summary>
        public static string title_igredient_name {
            get {
                return ResourceManager.GetString("title_igredient_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SỐ LƯỢNG.
        /// </summary>
        public static string title_igredient_quantity {
            get {
                return ResourceManager.GetString("title_igredient_quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HÌNH ẢNH - VIDEO.
        /// </summary>
        public static string title_image_video {
            get {
                return ResourceManager.GetString("title_image_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LINK HƯỚNG DẪN CHI TIẾT.
        /// </summary>
        public static string title_link_how_to_use {
            get {
                return ResourceManager.GetString("title_link_how_to_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LINK VIDEO.
        /// </summary>
        public static string title_link_video {
            get {
                return ResourceManager.GetString("title_link_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MÃ NGUỒN MỞ.
        /// </summary>
        public static string title_open_source {
            get {
                return ResourceManager.GetString("title_open_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TÊN MÓN ĂN.
        /// </summary>
        public static string title_recipe_name {
            get {
                return ResourceManager.GetString("title_recipe_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HÌNH ẢNH ĐI KÈM.
        /// </summary>
        public static string title_relative_image {
            get {
                return ResourceManager.GetString("title_relative_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by:.
        /// </summary>
        public static string title_sort_box {
            get {
                return ResourceManager.GetString("title_sort_box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bước.
        /// </summary>
        public static string title_step {
            get {
                return ResourceManager.GetString("title_step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THỜI GIAN - NHÓM - MỨC ĐỘ.
        /// </summary>
        public static string title_time_group_level {
            get {
                return ResourceManager.GetString("title_time_group_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HƯỚNG DẪN THỰC HIỆN.
        /// </summary>
        public static string title_tutorial {
            get {
                return ResourceManager.GetString("title_tutorial", resourceCulture);
            }
        }
    }
}
